%{
#include "DNALexerDefs.h"
#include "DNAParserDefs.h"

// #define DO_YYDEBUG

#ifdef DO_YYDEBUG
#define YYDEBUG 1
#endif
#include "dna_ypp.hpp"

#include "DNAVisGroup.h"

// Because our token type contains objects of type string, which
// require correct copy construction (and not simply memcpying), we
// cannot use bison's built-in auto-stack-grow feature.  As an easy
// solution, we ensure here that we have enough yacc stack to start
// with, and that it doesn't ever try to grow.
#define YYINITDEPTH 1000
#define YYMAXDEPTH 1000

////////////////////////////////////////////////////////////////////
// Static variables
////////////////////////////////////////////////////////////////////

static DNALoader* _loader = nullptr;
static DNAStorage* _store = nullptr;
static DNAGroup* _cur_comp = nullptr;

////////////////////////////////////////////////////////////////////
// Defining the interface to the parser.
////////////////////////////////////////////////////////////////////

void dna_init_parser(std::istream &in, const std::string &filename,
                     DNALoader* loader, DNAStorage* store,
                     DNAGroup* root) {
#ifdef DO_YYDEBUG
  dnayydebug = 1;
#endif
  dna_init_lexer(in, filename);
  _loader = loader;
  _store = store;
  _cur_comp = root;
}

void dna_cleanup_parser() {
  _loader = nullptr;
  _store = nullptr;
  _cur_comp = nullptr;
}

%}

%token <u.int64> SIGNED_INTEGER
%token <u.uint64> UNSIGNED_INTEGER
%token <u.real> FLOAT_REAL
%token <str> UNQUOTED_STRING QUOTED_STRING

%token STORE_SUIT_POINT
%token DNAGROUP
%token VISGROUP
%token VIS
%token DNA_STREET_POINT
%token DNA_FRONT_DOOR_POINT
%token DNA_SIDE_DOOR_POINT
%token DNA_COGHQ_IN_POINT
%token DNA_COGHQ_OUT_POINT
%token SUIT_EDGE
%token BATTLE_CELL
%token PROP
%token POS
%token HPR
%token SCALE
%token CODE
%token COLOR
%token MODEL
%token STORE_NODE
%token SIGN
%token BASELINE
%token WIDTH
%token HEIGHT
%token STOMP
%token STUMBLE
%token INDENT
%token WIGGLE
%token KERN
%token DNATEXT
%token LETTERS
%token STORE_FONT
%token FLAT_BUILDING
%token WALL
%token WINDOWS
%token COUNT
%token CORNICE
%token LANDMARK_BUILDING
%token TITLE
%token ARTICLE
%token BUILDING_TYPE
%token DOOR
%token STORE_TEXTURE
%token STREET
%token TEXTURE
%token GRAPHIC
%token HOODMODEL
%token PLACEMODEL
%token FLAGS
%token NODE
%token FLAT_DOOR
%token ANIM
%token CELL_ID
%token ANIM_PROP
%token INTERACTIVE_PROP
%token ANIM_BUILDING

%type <u.real> number
%type <str> string
%type <str_vec> string_opt_list
%type <point3> lpoint3f
%type <u.uint64> suitpointtype
%type <str> vis
%type <str> flags

%%

dna : dna object
    | object
;

object : suitpoint
       | group
       | model
       | font
       | store_texture
;

number : UNSIGNED_INTEGER
{
  $$ = (double)$1;
}
       | SIGNED_INTEGER
{
  $$ = (double)$1;
}
       | FLOAT_REAL
{
  $$ = $1;
}

lpoint3f : number number number
{
}

suitpoint : STORE_SUIT_POINT '[' number ',' suitpointtype ',' lpoint3f ']'
{
}
          | STORE_SUIT_POINT '[' number ',' suitpointtype ',' lpoint3f ',' number ']'
{
}

suitpointtype : DNA_STREET_POINT
{
  #undef DNA_STREET_POINT
}
              | DNA_FRONT_DOOR_POINT
{
  #undef DNA_FRONT_DOOR_POINT
}
              | DNA_SIDE_DOOR_POINT
{
  #undef DNA_SIDE_DOOR_POINT
}
              | DNA_COGHQ_IN_POINT
{
  #undef DNA_COGHQ_IN_POINT
}
              | DNA_COGHQ_OUT_POINT
{
  #undef DNA_COGHQ_OUT_POINT
}

string : QUOTED_STRING
{
  $$ = $1;
}
       | UNQUOTED_STRING
{
  $$ = $1;
}

dnagroupdef : DNAGROUP string
{
  DNAGroup* g = new DNAGroup($2);
  g->set_parent(_cur_comp);
  g->set_vis_group(_cur_comp->get_vis_group());
  _cur_comp->add(g);
  _cur_comp = g;
}

dnanodedef : NODE string
{
}

visgroupdef : VISGROUP string
{
  DNAGroup* g = new DNAVisGroup($2);
  g->set_parent(_cur_comp);
  _cur_comp->add(g);
  _cur_comp = g;
  _store->store_DNA_vis_group((DNAVisGroup*)g);
}

dnagroup : dnagroupdef '[' subgroup_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}

visgroup : visgroupdef '[' subvisgroup_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}

string_opt_list : string_opt_list string
{
  $1.push_back($2);
  $$ = $1;
}
                | empty
{
  $$ = {};
}

vis : VIS '[' string string_opt_list ']'
{
  DNAVisGroup* g = (DNAVisGroup*)_cur_comp;
  g->add_visible($3);
  for (auto& vis : $4)
    g->add_visible(vis);
}

empty :
;

group : dnagroup
      | visgroup
      | dnanode
      | windows
      | cornice
      | door
;

dnanode : prop
        | sign
        | signbaseline
        | signtext
        | flatbuilding
        | wall
        | landmarkbuilding
        | street
        | signgraphic
        | dnanode_grp
;

dnanode_grp : dnanodedef '[' subdnanode_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}

sign : signdef '[' subprop_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}

signgraphic : signgraphicdef '[' subsigngraphic_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}

prop : propdef '[' subprop_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}
     | animpropdef '[' subanimprop_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}
     | interactivepropdef '[' subinteractiveprop_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}

signbaseline : baselinedef '[' subbaseline_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}

signtext : textdef '[' subtext_list ']'
;

flatbuilding : flatbuildingdef '[' subflatbuilding_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}

wall : walldef '[' subwall_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}

windows : windowsdef '[' subwindows_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}

cornice : cornicedef '[' subcornice_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}

landmarkbuilding : landmarkbuildingdef '[' sublandmarkbuilding_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}
                 | animbuildingdef '[' subanimbuilding_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}

street : streetdef '[' substreet_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}

door : doordef '[' subdoor_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}
     | flatdoordef '[' subdoor_list ']'
{
  _cur_comp = _cur_comp->get_parent();
}

propdef : PROP string
{
}

animpropdef : ANIM_PROP string
{
}

interactivepropdef : INTERACTIVE_PROP string
{
}

flatbuildingdef : FLAT_BUILDING string
{
}

walldef : WALL
{
}

windowsdef : WINDOWS
{
}

cornicedef : CORNICE
{
}

landmarkbuildingdef : LANDMARK_BUILDING string
{
}

animbuildingdef : ANIM_BUILDING string
{
}

doordef : DOOR
{
}

flatdoordef : FLAT_DOOR
{
}

streetdef : STREET string
{
}

signdef : SIGN
{
}

signgraphicdef : GRAPHIC
{
}

baselinedef : BASELINE
{
}

textdef : DNATEXT
{
}

suitedge : SUIT_EDGE '[' number number ']'
{
}

battlecell : BATTLE_CELL '[' number number lpoint3f ']'
{
}

subgroup_list : subgroup_list group
              | empty
;

subvisgroup_list : subvisgroup_list group
                 | subvisgroup_list suitedge
                 | subvisgroup_list battlecell
                 | subvisgroup_list vis
                 | empty
;

pos : POS '[' lpoint3f ']'
{
}

hpr : HPR '[' lpoint3f ']'
{
}

scale : SCALE '[' lpoint3f ']'
{
}

flags : FLAGS '[' string ']'
{
}

dnanode_sub : group
            | pos
            | hpr
            | scale
;

dnaprop_sub : prop_code
            | prop_color
;

dnaanimprop_sub : anim
;

dnainteractiveprop_sub : CELL_ID '[' number ']'
{
}

anim : ANIM '[' string ']'
{
}

baseline_sub : baseline_code
             | baseline_color
             | baseline_width
             | baseline_height
             | indent
             | kern
             | stomp
             | stumble
             | wiggle
             | flags
;

text_sub : LETTERS '[' string ']'
{
}

signgraphic_sub : signgraphic_width
                | signgraphic_height
                | signgraphic_code
                | signgraphic_color
;

flatbuilding_sub : flatbuilding_width
;

wall_sub : wall_height
         | wall_code
         | wall_color
;

windows_sub : windows_code
            | windows_color
            | windowcount
;

cornice_sub : cornice_code
            | cornice_color
;

landmarkbuilding_sub : landmarkbuilding_code
                     | title
                     | article
                     | building_type
                     | lb_wall_color
;

animbuilding_sub : ab_anim
;

door_sub : door_code
         | door_color
;

street_sub : street_code
           | texture
           | street_color
;

texture : TEXTURE '[' string ']'
{
}

street_color : COLOR '[' number number number number ']'
{
}

title : TITLE '[' string ']'
{
}

article : ARTICLE '[' string ']'
{
}

building_type : BUILDING_TYPE '[' string ']'
{
}

lb_wall_color : COLOR '[' number number number number ']'
{
}

ab_anim : ANIM '[' string ']'
{
}

windowcount : COUNT '[' number ']'
{
}

baseline_width : WIDTH '[' number ']'
{
}

signgraphic_width : WIDTH '[' number ']'
{
}

flatbuilding_width : WIDTH '[' number ']'
{
}

baseline_height : HEIGHT '[' number ']'
{
}

signgraphic_height : HEIGHT '[' number ']'
{
}

wall_height : HEIGHT '[' number ']'
{
}

stomp : STOMP '[' number ']'
{
}

indent : INDENT '[' number ']'
{
}

kern : KERN '[' number ']'
{
}

stumble : STUMBLE '[' number ']'
{
}

wiggle : WIGGLE '[' number ']'
{
}

prop_code : CODE '[' string ']'
{
}

landmarkbuilding_code : CODE '[' string ']'
{
}

baseline_code : CODE '[' string ']'
{
}

door_code : CODE '[' string ']'
{
}

signgraphic_code : CODE '[' string ']'
{
}

cornice_code : CODE '[' string ']'
{
}

street_code : CODE '[' string ']'
{
}

wall_code : CODE '[' string ']'
{
}

windows_code : CODE '[' string ']'
{
}

prop_color : COLOR '[' number number number number ']'
{
}

baseline_color : COLOR '[' number number number number ']'
{
}

door_color : COLOR '[' number number number number ']'
{
}

signgraphic_color : COLOR '[' number number number number ']'
{
}

cornice_color : COLOR '[' number number number number ']'
{
}

wall_color : COLOR '[' number number number number ']'
{
}

windows_color : COLOR '[' number number number number ']'
{
}

subprop_list : subprop_list dnanode_sub
             | subprop_list dnaprop_sub
             | empty
;

subanimprop_list : subanimprop_list dnanode_sub
                 | subanimprop_list dnaprop_sub
                 | subanimprop_list dnaanimprop_sub
                 | empty
;

subinteractiveprop_list : subinteractiveprop_list dnanode_sub
                        | subinteractiveprop_list dnaprop_sub
                        | subinteractiveprop_list dnaanimprop_sub
                        | subinteractiveprop_list dnainteractiveprop_sub
                        | empty
;

subbaseline_list : subbaseline_list dnanode_sub
                 | subbaseline_list baseline_sub
                 | empty
;

subtext_list : subtext_list dnanode_sub
             | subtext_list text_sub
             | empty
;

subdnanode_list : subdnanode_list dnanode_sub
                | empty
;

subsigngraphic_list : subsigngraphic_list dnanode_sub
                    | subsigngraphic_list signgraphic_sub
                    | empty
;

subflatbuilding_list : subflatbuilding_list dnanode_sub
                     | subflatbuilding_list flatbuilding_sub
                     | empty
;

subwall_list : subwall_list dnanode_sub
             | subwall_list wall_sub
             | empty
;

subwindows_list : subwindows_list dnanode_sub
                | subwindows_list windows_sub
                | empty
;

subcornice_list : subcornice_list dnanode_sub
                | subcornice_list cornice_sub
                | empty
;

sublandmarkbuilding_list : sublandmarkbuilding_list dnanode_sub
                         | sublandmarkbuilding_list landmarkbuilding_sub
                         | empty
;

subanimbuilding_list : subanimbuilding_list dnanode_sub
                     | subanimbuilding_list landmarkbuilding_sub
                     | subanimbuilding_list animbuilding_sub
                     | empty
;

subdoor_list : subdoor_list dnanode_sub
             | subdoor_list door_sub
             | empty
;

substreet_list : substreet_list dnanode_sub
               | substreet_list street_sub
               | empty
;

modeldef : MODEL string
{
}
         | HOODMODEL string
{
}
         | PLACEMODEL string
{
}

model : modeldef '[' modelnode_list ']'
;

modelnode_list : modelnode_list node
               | empty
;

node : STORE_NODE '[' string string ']'
{
}
     | STORE_NODE '[' string string string ']'
{
}

store_texture : STORE_TEXTURE '[' string string ']'
{
}
              | STORE_TEXTURE '[' string string string ']'
{
}

font : STORE_FONT '[' string string string ']'
{
}
