#pragma once
#include "types.h"

/* Message boolean macros */
#define SUCCESS 1
#define FAILURE 0

/* Defined context values */
const uint32_t STATESERVER_CONTEXT_WAKE_CHILDREN = 1001;

/* Msgtype limits enum */
enum MsgtypeRanges {
    // Control range
    CONTROL_MSGTYPE_MIN = 9000,
    CONTROL_MSGTYPE_MAX = 9999,
    // ClientAgent range
    CLIENTAGENT_MSGTYPE_MIN = 1000,
    CLIENTAGENT_MSGTYPE_MAX = 1999,
    // StateServer range
    STATESERVER_MSGTYPE_MIN = 2000,
    STATESERVER_MSGTYPE_MAX = 2999,
    // DatabaseServer range
    DBSERVER_MSGTYPE_MIN = 3000,
    DBSERVER_MSGTYPE_MAX = 3999,
};

/* Message type definitions */
enum MessageTypes {
    // Reserved
    RESERVED_MSG_TYPE = 0,

    // Control messages
    CONTROL_ADD_CHANNEL        = 9000,
    CONTROL_REMOVE_CHANNEL     = 9010,
    CONTROL_ADD_RANGE          = 9020,
    CONTROL_REMOVE_RANGE       = 9030,
    CONTROL_ADD_POST_REMOVE    = 9040,
    CONTROL_CLEAR_POST_REMOVES = 9050,
    CONTROL_SET_CON_NAME       = 9060,
    CONTROL_SET_CON_URL        = 9070,
    CONTROL_LOG_MESSAGE        = 9080,

    // ClientAgent messages
    CLIENTAGENT_SET_STATE                 = 1000,
    CLIENTAGENT_SET_CLIENT_ID             = 1010,
    CLIENTAGENT_SEND_DATAGRAM             = 1020,
    CLIENTAGENT_EJECT                     = 1030,
    CLIENTAGENT_DROP                      = 1040,
    CLIENTAGENT_GET_NETWORK_ADDRESS       = 1050,
    CLIENTAGENT_GET_NETWORK_ADDRESS_RESP  = 1052,
    CLIENTAGENT_DECLARE_OBJECT            = 1060,
    CLIENTAGENT_UNDECLARE_OBJECT          = 1062,
    CLIENTAGENT_ADD_SESSION_OBJECT        = 1070,
    CLIENTAGENT_REMOVE_SESSION_OBJECT     = 1072,
    CLIENTAGENT_SET_FIELDS_SENDABLE       = 1080,
    CLIENTAGENT_GET_TLVS                  = 1090,
    CLIENTAGENT_GET_TLVS_RESP             = 1092,
    CLIENTAGENT_OPEN_CHANNEL              = 1100,
    CLIENTAGENT_CLOSE_CHANNEL             = 1102,
    CLIENTAGENT_ADD_POST_REMOVE           = 1200,
    CLIENTAGENT_CLEAR_POST_REMOVES        = 1202,
    CLIENTAGENT_SET_OBJECT_RELOCATABLE    = 1300,
    CLIENTAGENT_ADD_INTEREST              = 1400,
    CLIENTAGENT_ADD_INTEREST_MULTIPLE     = 1402,
    CLIENTAGENT_ADD_INTEREST_OBJECTS      = 1404,
    CLIENTAGENT_REMOVE_INTEREST           = 1406,
    CLIENTAGENT_DONE_INTEREST_RESP        = 1408,
    CLIENTAGENT_EXTAGENT_MESSAGE          = 1410,
    CLIENTAGENT_EXTAGENT_RESPONSE         = 1412,

    // StateServer control messages
    STATESERVER_CREATE_OBJECT_WITH_REQUIRED       = 2000,
    STATESERVER_CREATE_OBJECT_WITH_REQUIRED_OTHER = 2002,
    STATESERVER_BOUNCE_MESSAGE                    = 2010,
    STATESERVER_DELETE_AI_OBJECTS                 = 2020,
    // StateServer object messages
    STATESERVER_OBJECT_GET_FIELD         = 2200,
    STATESERVER_OBJECT_GET_FIELD_RESP    = 2202,
    STATESERVER_OBJECT_GET_FIELDS        = 2210,
    STATESERVER_OBJECT_GET_FIELDS_RESP   = 2212,
    STATESERVER_OBJECT_GET_ALL           = 2220,
    STATESERVER_OBJECT_GET_ALL_RESP      = 2222,
    STATESERVER_OBJECT_SET_FIELD         = 2230,
    STATESERVER_OBJECT_SET_FIELDS        = 2232,
    STATESERVER_OBJECT_DELETE_FIELD_RAM  = 2240,
    STATESERVER_OBJECT_DELETE_FIELDS_RAM = 2242,
    STATESERVER_OBJECT_DELETE_RAM        = 2244,
    // StateServer visibility messages
    STATESERVER_OBJECT_SET_LOCATION                       = 2400,
    STATESERVER_OBJECT_CHANGING_LOCATION                  = 2410,
    STATESERVER_OBJECT_ENTER_LOCATION_WITH_REQUIRED       = 2420,
    STATESERVER_OBJECT_ENTER_LOCATION_WITH_REQUIRED_OTHER = 2422,
    STATESERVER_OBJECT_GET_LOCATION                       = 2430,
    STATESERVER_OBJECT_GET_LOCATION_RESP                  = 2432,
    STATESERVER_OBJECT_LOCATION_ACK                       = 2440,
    STATESERVER_OBJECT_SET_AI                             = 2450,
    STATESERVER_OBJECT_CHANGING_AI                        = 2460,
    STATESERVER_OBJECT_ENTER_AI_WITH_REQUIRED             = 2470,
    STATESERVER_OBJECT_ENTER_AI_WITH_REQUIRED_OTHER       = 2472,
    STATESERVER_OBJECT_GET_AI                             = 2480,
    STATESERVER_OBJECT_GET_AI_RESP                        = 2482,
    STATESERVER_OBJECT_SET_OWNER                          = 2490,
    STATESERVER_OBJECT_CHANGING_OWNER                     = 2500,
    STATESERVER_OBJECT_ENTER_OWNER_WITH_REQUIRED_OTHER    = 2510,
    STATESERVER_OBJECT_GET_OWNER                          = 2520,
    STATESERVER_OBJECT_GET_OWNER_RESP                     = 2522,
    STATESERVER_OBJECT_ENTER_INTEREST_WITH_REQUIRED       = 2530,
    STATESERVER_OBJECT_ENTER_INTEREST_WITH_REQUIRED_OTHER = 2532,
    // StateServer parent-method messages
    STATESERVER_OBJECT_GET_ZONE_OBJECTS     = 2700,
    STATESERVER_OBJECT_GET_ZONES_OBJECTS    = 2702,
    STATESERVER_OBJECT_GET_CHILDREN         = 2710,
    STATESERVER_OBJECT_GET_COUNT            = 2720, // TODO: Unused??
    STATESERVER_OBJECT_GET_COUNT_RESP       = 2722,
    STATESERVER_OBJECT_GET_CHILD_COUNT      = 2730, // TODO: Implement
    STATESERVER_OBJECT_GET_CHILD_COUNT_RESP = 2732, // TODO: Implement
    STATESERVER_OBJECT_DELETE_ZONE          = 2740, // TODO: Implement
    STATESERVER_OBJECT_DELETE_ZONES         = 2742, // TODO: Implement
    STATESERVER_OBJECT_DELETE_CHILDREN      = 2744,
    STATESERVER_GET_ACTIVE_ZONES            = 2750,
    STATESERVER_GET_ACTIVE_ZONES_RESP       = 2752,
    // DBSS object messages
    DBSS_OBJECT_ACTIVATE_WITH_DEFAULTS       = 2900,
    DBSS_OBJECT_ACTIVATE_WITH_DEFAULTS_OTHER = 2902,
    DBSS_OBJECT_GET_ACTIVATED                = 2910,
    DBSS_OBJECT_GET_ACTIVATED_RESP           = 2912,
    DBSS_OBJECT_DELETE_FIELD_RAM             = 2920,
    DBSS_OBJECT_DELETE_FIELDS_RAM            = 2922,
    DBSS_OBJECT_DELETE_DISK                  = 2924,

    // DatabaseServer messages
    DBSERVER_CREATE_OBJECT                    = 3000,
    DBSERVER_CREATE_OBJECT_RESP               = 3002,
    DBSERVER_OBJECT_GET_FIELD                 = 3010,
    DBSERVER_OBJECT_GET_FIELD_RESP            = 3012,
    DBSERVER_OBJECT_GET_FIELDS                = 3014,
    DBSERVER_OBJECT_GET_FIELDS_RESP           = 3016,
    DBSERVER_OBJECT_GET_ALL                   = 3020,
    DBSERVER_OBJECT_GET_ALL_RESP              = 3022,
    DBSERVER_OBJECT_SET_FIELD                 = 3030,
    DBSERVER_OBJECT_SET_FIELDS                = 3032,
    DBSERVER_OBJECT_SET_FIELD_IF_EQUALS       = 3040,
    DBSERVER_OBJECT_SET_FIELD_IF_EQUALS_RESP  = 3042,
    DBSERVER_OBJECT_SET_FIELDS_IF_EQUALS      = 3044,
    DBSERVER_OBJECT_SET_FIELDS_IF_EQUALS_RESP = 3046,
    DBSERVER_OBJECT_SET_FIELD_IF_EMPTY        = 3050,
    DBSERVER_OBJECT_SET_FIELD_IF_EMPTY_RESP   = 3052,
    DBSERVER_OBJECT_DELETE_FIELD              = 3060,
    DBSERVER_OBJECT_DELETE_FIELDS             = 3062,
    DBSERVER_OBJECT_DELETE                    = 3070,

    // BungeeCord messages
    BUNGEECORD_ROUTE_MESSAGE = 4000,
    BUNGEECORD_ROUTE_MESSAGES = 4010,
};
